export const NEXT_QUESTION = "NEXT_QUESTION";
export const END_QUIZ = "END_QUIZ";
export const GENERATE_QUIZ = "GENERATE_QUIZ";
export const FETCH_QUIZ_REQUEST = "FETCH_QUIZ_REQUEST";
export const FETCH_QUIZ_ERROR = "FETCH_QUIZ_ERROR";
export const FETCH_QUIZ_SUCCESS = "FETCH_QUIZ_SUCCESS";
